services:
    Fusonic\MessengerMailerBundle\EventSubscriber\AttachmentEmailEventSubscriber:
        arguments:
            $handler: '@messenger_mailer.attachment_handler'
        tags:
            - { name: kernel.event_subscriber }

    Fusonic\MessengerMailerBundle\EmailAttachmentHandler\FilesystemAttachmentHandler:
        arguments:
            $attachmentsDirectory: "%kernel.project_dir%/var/email-attachments"
