include:
    - local: 'gitlab-cli/build.yml'
    - local: 'gitlab-cli/tests.yml'
    - local: 'gitlab-cli/publish.yml'

stages:
    - ci
    - test
    - publish

variables:
    DOCKER_IMAGE: docker:19.03
    DOCKER_DIND_IMAGE: docker:19.03-dind
    PHP_CLI_IMAGE: $CI_REGISTRY_IMAGE/php-cli:latest


