stages:
    - publish
    - test

publish:test-utilities:master:
    stage: publish
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master
        changes:
            - packages/test-utilities/**/*
    script:
        - ./bin/publish-package.sh master

publish:test-utilities:tag:
    stage: publish
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master
        changes:
            - packages/test-utilities/**/*
    when: manual
    script:
        - ./bin/publish-package.sh tag

test:package-integration:
    stage: test
    image: php
    script:
        - curl -sS https://getcomposer.org/installer | php -- --install-dir=. --filename=composer
        - composer init -n
        - composer require arjanfrans/test

