stages:
    - publish
    - test

publish:test-utilities:master:
    stage: publish
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master
        changes:
            - packages/test-utilities/**/*
    script:
        - ./bin/publish-package.sh master

publish:test-utilities:tag:
    stage: publish
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master
        changes:
            - packages/test-utilities/**/*
    when: manual
    script:
        - ./bin/publish-package.sh tag

test:phpunit:test-utilities:
    stage: test
    image: php:7.4-cli
    script:
        - cd packages/test-utilities
        - curl -sS https://getcomposer.org/installer | php --
        - php composer.phar install
        - vendor/bin/phpunit

test:package-integration:
    stage: test
    script:
        - apt-get update && apt-get install -y --no-install-recommends php
        - curl -sS https://getcomposer.org/installer | php --
        - php composer.phar init -n
        - php composer.phar require arjanfrans/test

