stages:
    - ci
    - test
    - publish

variables:
    DOCKER_IMAGE: docker:19.03
    DOCKER_DIND_IMAGE: docker:19.03-dind
    PHP_CLI_IMAGE: $CI_REGISTRY_IMAGE/php-cli:latest

ci:build:php-cli-image:
    stage: ci
    image: ${DOCKER_IMAGE}
    services:
        - ${DOCKER_DIND_IMAGE}
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build --pull --cache-from $PHP_CLI_IMAGE --cache-from master -f docker/php-cli/Dockerfile --tag $PHP_CLI_IMAGE .
        - docker push $PHP_CLI_IMAGE
    interruptible: true
    only:
        refs:
            - master
        changes:
            - docker/php-cli/**/*

test:phpunit:test-utilities:
    stage: test
    image: ${PHP_CLI_IMAGE}
    only:
        changes:
            - packages/test-utilities/**/*
    interruptible: true
    script:
        - cd packages/test-utilities
        - composer install
        - vendor/bin/phpunit

test:package-integration:
    stage: test
    image: ${PHP_CLI_IMAGE}
    interruptible: true
    script:
        - composer init -n
        - composer require arjanfrans/test

publish:test-utilities:master:
    stage: publish
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master
        changes:
            - packages/test-utilities/**/*
    script:
        - ./bin/publish-package.sh master

publish:test-utilities:tag:
    stage: publish
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master
        changes:
            - packages/test-utilities/**/*
    when: manual
    script:
        - ./bin/publish-package.sh tag


