stages:
    - publish
    - test

publish:test-utilities:master:
    stage: publish
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master
        changes:
            - packages/test-utilities/**/*
    script:
        - ./bin/publish-package.sh master

publish:test-utilities:tag:
    stage: publish
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master
        changes:
            - packages/test-utilities/**/*
    when: manual
    script:
        - ./bin/publish-package.sh tag

test:package-integration:
    stage: test
    script:
        - apt update && apt install -y --no-install-recommends php
        - curl -sS https://getcomposer.org/installer | php --
        - php composer.phar init -n
        - php composer.phar require arjanfrans/test

