include:
    - local: 'gitlab-ci/build.yml'
    - local: 'gitlab-ci/tests.yml'
    - local: 'gitlab-ci/publish.yml'

stages:
    - ci
    - test
    - publish

variables:
    DOCKER_IMAGE: docker:19.03
    DOCKER_DIND_IMAGE: docker:19.03-dind
    PHP_CLI_IMAGE: $CI_REGISTRY_IMAGE/php-cli:latest


