include:
    - local: 'ci/_includes.yml'
    - local: 'ci/packages/test-utilities.yml'

stages:
    - install
    - test
    - publish

variables:
    DOCKER_IMAGE: docker:19.03
    DOCKER_DIND_IMAGE: docker:19.03-dind
    PHP_VERSION: '7.4'
    PHP_DOCKER_RELEASE: 'buster'


