php-cli-image:
    stage: ci
    image: ${DOCKER_IMAGE}
    services:
        - ${DOCKER_DIND_IMAGE}
    script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker build --pull --cache-from $PHP_CLI_IMAGE --cache-from master -f docker/php-cli/Dockerfile --tag $PHP_CLI_IMAGE .
        - docker push $PHP_CLI_IMAGE
    interruptible: true
    only:
        refs:
            - master
        changes:
            - docker/php-cli/**/*

