.publish-tag:
    stage: publish
    variables:
        PUBLISH: tag
    script:
        - ./bin/publish-package.sh $PUBLISH
    when: manual

.publish-master:
    extends: .publish-tag
    variables:
        PUBLISH: master
    only:
        refs:
            - master
    when: always

test-utilities:master:
    extends: .publish-master
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        changes:
            - packages/test-utilities/**/*

test-utilities:tag:
    extends: .publish-tag
    variables:
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        changes:
            - packages/test-utilities/**/*

