.publish:
    stage: publish
    script:
        - ./bin/publish-package.sh $PUBLISH
    only:
        changes:
            - $PACKAGE/**/*

test-utilities:master:
    extends: .publish
    variables:
        PUBLISH: master
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    only:
        refs:
            - master

test-utilities:tag:
    extends: .publish
    variables:
        PUBLISH: tag
        PACKAGE: packages/test-utilities
        REPOSITORY: git@github.com:arjanfrans/test.git
    when: manual

